# Generated by Django 3.0.2 on 2020-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0002_auto_20200123_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('attribute', models.CharField(choices=[('status_seat', 'seat'), ('status_meetingroom', 'meetingroom')], default='status_seat', max_length=50)),
            ],
        ),
    ]
